name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/reusable-tests.yml

  deploy:
    name: Deploy to EC2
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "~/alumnx-vector-db-prod" ]; then
              git clone https://github.com/alumnx-ai-labs/alumnx-vector-db.git ~/alumnx-vector-db-prod
            fi
            cd ~/alumnx-vector-db-prod && git fetch origin && git checkout main && git pull origin main && bash deploy.sh main 8012 alumnx-vector-db-prod
